export const LOGOUT = 'LOGOUT'

export const INITIATE_LOGOUT = 'INITIATE_LOGOUT'

export const INITIATE_LOGIN = 'INITIATE_FB_LOGIN'

export const FB_LOGIN = 'FB_LOGIN'
export const FB_LOGIN_SUCCESS = 'FB_LOGIN_SUCCESS'
export const FB_LOGIN_FAIL = 'FB_LOGIN_FAIL'

export const AUTH_FROM_LS = 'AUTH_FROM_LS'

export const INITIATE_GETTING_CONTACTS = 'INITIATE_GETTING_CONTACTS'

export const REQ_CONT = 'REQ_CONT'
export const REQ_CONT_SUCCESS = 'REQ_CONT_SUCCESS'
export const REQ_CONT_FAIL = 'REQ_CONT_FAIL'

export const INITIATE_GETTING_ONE_CONTACTS = 'INITIATE_GETTING_ONE_CONTACTS'

export const REQ_ONE_RELOAD = 'REQ_ONE_RELOAD'
export const REQ_ONE_RELOAD_SUCCESS = 'REQ_ONE_RELOAD_SUCCESS'
export const REQ_ONE_RELOAD_FAIL = 'REQ_ONE_RELOAD_FAIL'
